services:
  - type: web
    name: dummy
    env: node
    repo: https://github.com/djodjo02130/dummy-render.git # optional
    pullRequestPreviewsEnabled: true # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    buildCommand: npm i
    startCommand: node ./app.js
    envVars:
    - key: PORT
      value: 10000
